# Generated by Django 5.1.3 on 2024-11-23 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departmenthead'),
        ),
    ]
